[workspace]
authors = ["Ericsii <ericfengx@foxmail.com>"]
channels = ["nvidia", "conda-forge"]
name = "IsaacLab-pixi"
platforms = ["linux-64"]
version = "0.1.0"

[activation.env]
ISAAC_PATH = "$PIXI_PROJECT_ROOT/.pixi/envs/default/lib/python3.11/site-packages/isaacsim"
ISAACLAB_PATH = "$PIXI_PROJECT_ROOT/IsaacLab"

[system-requirements]
cuda = "12.8"
libc = { family = "glibc", version = "2.35" }

[dependencies]
python = "3.11.*"
compilers = "*"
cmake = "<4.0"
pkg-config = "*"
make = "*"
ninja = "*"

[pypi-dependencies]
torch = { version = "==2.7.0", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = "==0.22.0", index = "https://download.pytorch.org/whl/cu128" }
isaacsim = { version = "==5.0.0", extras = [
  "all",
  "extscache",
], index = "https://pypi.nvidia.com" }
isaaclab = { path = "IsaacLab/source/isaaclab", editable = true }
isaaclab_assets = { path = "IsaacLab/source/isaaclab_assets", editable = true }
isaaclab_tasks = { path = "IsaacLab/source/isaaclab_tasks", editable = true }
isaaclab_mimic = { path = "IsaacLab/source/isaaclab_mimic", editable = true, extras = [
  "all",
] }
isaaclab_rl = { path = "IsaacLab/source/isaaclab_rl", editable = true, extras = [
  "all",
] }
